// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameEvent_EventType int32

const (
	GameEvent_GAME_START   GameEvent_EventType = 0
	GameEvent_PLAYER_DEATH GameEvent_EventType = 1
	GameEvent_GAME_OVER    GameEvent_EventType = 2
)

// Enum value maps for GameEvent_EventType.
var (
	GameEvent_EventType_name = map[int32]string{
		0: "GAME_START",
		1: "PLAYER_DEATH",
		2: "GAME_OVER",
	}
	GameEvent_EventType_value = map[string]int32{
		"GAME_START":   0,
		"PLAYER_DEATH": 1,
		"GAME_OVER":    2,
	}
)

func (x GameEvent_EventType) Enum() *GameEvent_EventType {
	p := new(GameEvent_EventType)
	*p = x
	return p
}

func (x GameEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[0].Descriptor()
}

func (GameEvent_EventType) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[0]
}

func (x GameEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameEvent_EventType.Descriptor instead.
func (GameEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11, 0}
}

// --- 顶层消息包 ---
type GamePacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GamePacket_Input
	//	*GamePacket_Snapshot
	//	*GamePacket_Event
	//	*GamePacket_Join
	Payload       isGamePacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GamePacket) Reset() {
	*x = GamePacket{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GamePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePacket) ProtoMessage() {}

func (x *GamePacket) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePacket.ProtoReflect.Descriptor instead.
func (*GamePacket) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *GamePacket) GetPayload() isGamePacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GamePacket) GetInput() *C2SInput {
	if x != nil {
		if x, ok := x.Payload.(*GamePacket_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *GamePacket) GetSnapshot() *S2CSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*GamePacket_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *GamePacket) GetEvent() *GameEvent {
	if x != nil {
		if x, ok := x.Payload.(*GamePacket_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *GamePacket) GetJoin() *C2SJoinRoom {
	if x != nil {
		if x, ok := x.Payload.(*GamePacket_Join); ok {
			return x.Join
		}
	}
	return nil
}

type isGamePacket_Payload interface {
	isGamePacket_Payload()
}

type GamePacket_Input struct {
	Input *C2SInput `protobuf:"bytes,1,opt,name=input,proto3,oneof"` // 客户端 -> 服务端：操作
}

type GamePacket_Snapshot struct {
	Snapshot *S2CSnapshot `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"` // 服务端 -> 客户端：状态同步
}

type GamePacket_Event struct {
	Event *GameEvent `protobuf:"bytes,3,opt,name=event,proto3,oneof"` // 服务端 -> 客户端：重要事件
}

type GamePacket_Join struct {
	Join *C2SJoinRoom `protobuf:"bytes,4,opt,name=join,proto3,oneof"` // 客户端 -> 服务端：加入
}

func (*GamePacket_Input) isGamePacket_Payload() {}

func (*GamePacket_Snapshot) isGamePacket_Payload() {}

func (*GamePacket_Event) isGamePacket_Payload() {}

func (*GamePacket_Join) isGamePacket_Payload() {}

type C2SJoinRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SJoinRoom) Reset() {
	*x = C2SJoinRoom{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SJoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SJoinRoom) ProtoMessage() {}

func (x *C2SJoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SJoinRoom.ProtoReflect.Descriptor instead.
func (*C2SJoinRoom) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *C2SJoinRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *C2SJoinRoom) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *C2SJoinRoom) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type C2SInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 客户端毫秒时间戳
	Move          *MoveCmd               `protobuf:"bytes,2,opt,name=move,proto3" json:"move,omitempty"`
	Charge        *ChargeCmd             `protobuf:"bytes,3,opt,name=charge,proto3" json:"charge,omitempty"`
	TargetTick    int64                  `protobuf:"varint,4,opt,name=target_tick,json=targetTick,proto3" json:"target_tick,omitempty"` // 客户端期望执行的目标tick（用于延迟补偿）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SInput) Reset() {
	*x = C2SInput{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SInput) ProtoMessage() {}

func (x *C2SInput) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SInput.ProtoReflect.Descriptor instead.
func (*C2SInput) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *C2SInput) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *C2SInput) GetMove() *MoveCmd {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *C2SInput) GetCharge() *ChargeCmd {
	if x != nil {
		return x.Charge
	}
	return nil
}

func (x *C2SInput) GetTargetTick() int64 {
	if x != nil {
		return x.TargetTick
	}
	return 0
}

type MoveCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dx            float32                `protobuf:"fixed32,1,opt,name=dx,proto3" json:"dx,omitempty"` // -1 到 1
	Dy            float32                `protobuf:"fixed32,2,opt,name=dy,proto3" json:"dy,omitempty"` // -1 到 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveCmd) Reset() {
	*x = MoveCmd{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveCmd) ProtoMessage() {}

func (x *MoveCmd) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveCmd.ProtoReflect.Descriptor instead.
func (*MoveCmd) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *MoveCmd) GetDx() float32 {
	if x != nil {
		return x.Dx
	}
	return 0
}

func (x *MoveCmd) GetDy() float32 {
	if x != nil {
		return x.Dy
	}
	return 0
}

type ChargeCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsCharging    bool                   `protobuf:"varint,1,opt,name=is_charging,json=isCharging,proto3" json:"is_charging,omitempty"` // true=按下, false=松开
	Angle         int32                  `protobuf:"varint,2,opt,name=angle,proto3" json:"angle,omitempty"`                             // 瞄准角度 0表示右，1表示上，2表示左，3表示下
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargeCmd) Reset() {
	*x = ChargeCmd{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeCmd) ProtoMessage() {}

func (x *ChargeCmd) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeCmd.ProtoReflect.Descriptor instead.
func (*ChargeCmd) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *ChargeCmd) GetIsCharging() bool {
	if x != nil {
		return x.IsCharging
	}
	return false
}

func (x *ChargeCmd) GetAngle() int32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

type C2SPlayerReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsReady       bool                   `protobuf:"varint,1,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SPlayerReady) Reset() {
	*x = C2SPlayerReady{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SPlayerReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SPlayerReady) ProtoMessage() {}

func (x *C2SPlayerReady) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SPlayerReady.ProtoReflect.Descriptor instead.
func (*C2SPlayerReady) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *C2SPlayerReady) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type PlayerInWaitingRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	IsReady       bool                   `protobuf:"varint,3,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInWaitingRoom) Reset() {
	*x = PlayerInWaitingRoom{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInWaitingRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInWaitingRoom) ProtoMessage() {}

func (x *PlayerInWaitingRoom) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInWaitingRoom.ProtoReflect.Descriptor instead.
func (*PlayerInWaitingRoom) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerInWaitingRoom) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerInWaitingRoom) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerInWaitingRoom) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type S2CWaitingRoomState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerInWaitingRoom `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	AllReady      bool                   `protobuf:"varint,2,opt,name=all_ready,json=allReady,proto3" json:"all_ready,omitempty"`
	HostUid       int64                  `protobuf:"varint,3,opt,name=host_uid,json=hostUid,proto3" json:"host_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CWaitingRoomState) Reset() {
	*x = S2CWaitingRoomState{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CWaitingRoomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CWaitingRoomState) ProtoMessage() {}

func (x *S2CWaitingRoomState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CWaitingRoomState.ProtoReflect.Descriptor instead.
func (*S2CWaitingRoomState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *S2CWaitingRoomState) GetPlayers() []*PlayerInWaitingRoom {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *S2CWaitingRoomState) GetAllReady() bool {
	if x != nil {
		return x.AllReady
	}
	return false
}

func (x *S2CWaitingRoomState) GetHostUid() int64 {
	if x != nil {
		return x.HostUid
	}
	return 0
}

type S2CSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	Tick          int64                  `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Players       []*PlayerState         `protobuf:"bytes,3,rep,name=players,proto3" json:"players,omitempty"`
	Beams         []*BeamState           `protobuf:"bytes,4,rep,name=beams,proto3" json:"beams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CSnapshot) Reset() {
	*x = S2CSnapshot{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CSnapshot) ProtoMessage() {}

func (x *S2CSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CSnapshot.ProtoReflect.Descriptor instead.
func (*S2CSnapshot) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *S2CSnapshot) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *S2CSnapshot) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *S2CSnapshot) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *S2CSnapshot) GetBeams() []*BeamState {
	if x != nil {
		return x.Beams
	}
	return nil
}

type PlayerState struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Uid                  int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	X                    float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Hp                   int32                  `protobuf:"varint,4,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp                int32                  `protobuf:"varint,5,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	IsDead               bool                   `protobuf:"varint,6,opt,name=is_dead,json=isDead,proto3" json:"is_dead,omitempty"`
	IsCharging           bool                   `protobuf:"varint,7,opt,name=is_charging,json=isCharging,proto3" json:"is_charging,omitempty"`
	ChargeStartTimeDelta int32                  `protobuf:"varint,8,opt,name=charge_start_time_delta,json=chargeStartTimeDelta,proto3" json:"charge_start_time_delta,omitempty"` // 相对当前时间的差值，用于前端平滑动画
	Username             string                 `protobuf:"bytes,9,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerState) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerState) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *PlayerState) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *PlayerState) GetIsDead() bool {
	if x != nil {
		return x.IsDead
	}
	return false
}

func (x *PlayerState) GetIsCharging() bool {
	if x != nil {
		return x.IsCharging
	}
	return false
}

func (x *PlayerState) GetChargeStartTimeDelta() int32 {
	if x != nil {
		return x.ChargeStartTimeDelta
	}
	return 0
}

func (x *PlayerState) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type BeamState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StartX        float32                `protobuf:"fixed32,2,opt,name=start_x,json=startX,proto3" json:"start_x,omitempty"`
	StartY        float32                `protobuf:"fixed32,3,opt,name=start_y,json=startY,proto3" json:"start_y,omitempty"`
	EndX          float32                `protobuf:"fixed32,4,opt,name=end_x,json=endX,proto3" json:"end_x,omitempty"`
	EndY          float32                `protobuf:"fixed32,5,opt,name=end_y,json=endY,proto3" json:"end_y,omitempty"`
	Width         float32                `protobuf:"fixed32,6,opt,name=width,proto3" json:"width,omitempty"`
	RemainingMs   int32                  `protobuf:"varint,7,opt,name=remaining_ms,json=remainingMs,proto3" json:"remaining_ms,omitempty"` // 剩余显示时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeamState) Reset() {
	*x = BeamState{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeamState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeamState) ProtoMessage() {}

func (x *BeamState) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeamState.ProtoReflect.Descriptor instead.
func (*BeamState) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *BeamState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BeamState) GetStartX() float32 {
	if x != nil {
		return x.StartX
	}
	return 0
}

func (x *BeamState) GetStartY() float32 {
	if x != nil {
		return x.StartY
	}
	return 0
}

func (x *BeamState) GetEndX() float32 {
	if x != nil {
		return x.EndX
	}
	return 0
}

func (x *BeamState) GetEndY() float32 {
	if x != nil {
		return x.EndY
	}
	return 0
}

func (x *BeamState) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BeamState) GetRemainingMs() int32 {
	if x != nil {
		return x.RemainingMs
	}
	return 0
}

type GameEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          GameEvent_EventType    `protobuf:"varint,1,opt,name=type,proto3,enum=pb.GameEvent_EventType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TargetUid     int64                  `protobuf:"varint,3,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"` // 死亡者或胜利者ID
	ExtraData     string                 `protobuf:"bytes,4,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`  // JSON: 战绩等
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

func (x *GameEvent) GetType() GameEvent_EventType {
	if x != nil {
		return x.Type
	}
	return GameEvent_GAME_START
}

func (x *GameEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GameEvent) GetTargetUid() int64 {
	if x != nil {
		return x.TargetUid
	}
	return 0
}

func (x *GameEvent) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x02pb\"\xba\x01\n" +
	"\n" +
	"GamePacket\x12$\n" +
	"\x05input\x18\x01 \x01(\v2\f.pb.C2SInputH\x00R\x05input\x12-\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x0f.pb.S2CSnapshotH\x00R\bsnapshot\x12%\n" +
	"\x05event\x18\x03 \x01(\v2\r.pb.GameEventH\x00R\x05event\x12%\n" +
	"\x04join\x18\x04 \x01(\v2\x0f.pb.C2SJoinRoomH\x00R\x04joinB\t\n" +
	"\apayload\"X\n" +
	"\vC2SJoinRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"\x91\x01\n" +
	"\bC2SInput\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\x04move\x18\x02 \x01(\v2\v.pb.MoveCmdR\x04move\x12%\n" +
	"\x06charge\x18\x03 \x01(\v2\r.pb.ChargeCmdR\x06charge\x12\x1f\n" +
	"\vtarget_tick\x18\x04 \x01(\x03R\n" +
	"targetTick\")\n" +
	"\aMoveCmd\x12\x0e\n" +
	"\x02dx\x18\x01 \x01(\x02R\x02dx\x12\x0e\n" +
	"\x02dy\x18\x02 \x01(\x02R\x02dy\"B\n" +
	"\tChargeCmd\x12\x1f\n" +
	"\vis_charging\x18\x01 \x01(\bR\n" +
	"isCharging\x12\x14\n" +
	"\x05angle\x18\x02 \x01(\x05R\x05angle\"+\n" +
	"\x0eC2SPlayerReady\x12\x19\n" +
	"\bis_ready\x18\x01 \x01(\bR\aisReady\"^\n" +
	"\x13PlayerInWaitingRoom\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x19\n" +
	"\bis_ready\x18\x03 \x01(\bR\aisReady\"\x80\x01\n" +
	"\x13S2CWaitingRoomState\x121\n" +
	"\aplayers\x18\x01 \x03(\v2\x17.pb.PlayerInWaitingRoomR\aplayers\x12\x1b\n" +
	"\tall_ready\x18\x02 \x01(\bR\ballReady\x12\x19\n" +
	"\bhost_uid\x18\x03 \x01(\x03R\ahostUid\"\x92\x01\n" +
	"\vS2CSnapshot\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x03R\x04tick\x12)\n" +
	"\aplayers\x18\x03 \x03(\v2\x0f.pb.PlayerStateR\aplayers\x12#\n" +
	"\x05beams\x18\x04 \x03(\v2\r.pb.BeamStateR\x05beams\"\xef\x01\n" +
	"\vPlayerState\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x0e\n" +
	"\x02hp\x18\x04 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x05 \x01(\x05R\x05maxHp\x12\x17\n" +
	"\ais_dead\x18\x06 \x01(\bR\x06isDead\x12\x1f\n" +
	"\vis_charging\x18\a \x01(\bR\n" +
	"isCharging\x125\n" +
	"\x17charge_start_time_delta\x18\b \x01(\x05R\x14chargeStartTimeDelta\x12\x1a\n" +
	"\busername\x18\t \x01(\tR\busername\"\xb0\x01\n" +
	"\tBeamState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\astart_x\x18\x02 \x01(\x02R\x06startX\x12\x17\n" +
	"\astart_y\x18\x03 \x01(\x02R\x06startY\x12\x13\n" +
	"\x05end_x\x18\x04 \x01(\x02R\x04endX\x12\x13\n" +
	"\x05end_y\x18\x05 \x01(\x02R\x04endY\x12\x14\n" +
	"\x05width\x18\x06 \x01(\x02R\x05width\x12!\n" +
	"\fremaining_ms\x18\a \x01(\x05R\vremainingMs\"\xce\x01\n" +
	"\tGameEvent\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.pb.GameEvent.EventTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"target_uid\x18\x03 \x01(\x03R\ttargetUid\x12\x1d\n" +
	"\n" +
	"extra_data\x18\x04 \x01(\tR\textraData\"<\n" +
	"\tEventType\x12\x0e\n" +
	"\n" +
	"GAME_START\x10\x00\x12\x10\n" +
	"\fPLAYER_DEATH\x10\x01\x12\r\n" +
	"\tGAME_OVER\x10\x02B\x06Z\x04./pbb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_game_proto_goTypes = []any{
	(GameEvent_EventType)(0),    // 0: pb.GameEvent.EventType
	(*GamePacket)(nil),          // 1: pb.GamePacket
	(*C2SJoinRoom)(nil),         // 2: pb.C2SJoinRoom
	(*C2SInput)(nil),            // 3: pb.C2SInput
	(*MoveCmd)(nil),             // 4: pb.MoveCmd
	(*ChargeCmd)(nil),           // 5: pb.ChargeCmd
	(*C2SPlayerReady)(nil),      // 6: pb.C2SPlayerReady
	(*PlayerInWaitingRoom)(nil), // 7: pb.PlayerInWaitingRoom
	(*S2CWaitingRoomState)(nil), // 8: pb.S2CWaitingRoomState
	(*S2CSnapshot)(nil),         // 9: pb.S2CSnapshot
	(*PlayerState)(nil),         // 10: pb.PlayerState
	(*BeamState)(nil),           // 11: pb.BeamState
	(*GameEvent)(nil),           // 12: pb.GameEvent
}
var file_game_proto_depIdxs = []int32{
	3,  // 0: pb.GamePacket.input:type_name -> pb.C2SInput
	9,  // 1: pb.GamePacket.snapshot:type_name -> pb.S2CSnapshot
	12, // 2: pb.GamePacket.event:type_name -> pb.GameEvent
	2,  // 3: pb.GamePacket.join:type_name -> pb.C2SJoinRoom
	4,  // 4: pb.C2SInput.move:type_name -> pb.MoveCmd
	5,  // 5: pb.C2SInput.charge:type_name -> pb.ChargeCmd
	7,  // 6: pb.S2CWaitingRoomState.players:type_name -> pb.PlayerInWaitingRoom
	10, // 7: pb.S2CSnapshot.players:type_name -> pb.PlayerState
	11, // 8: pb.S2CSnapshot.beams:type_name -> pb.BeamState
	0,  // 9: pb.GameEvent.type:type_name -> pb.GameEvent.EventType
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_game_proto_msgTypes[0].OneofWrappers = []any{
		(*GamePacket_Input)(nil),
		(*GamePacket_Snapshot)(nil),
		(*GamePacket_Event)(nil),
		(*GamePacket_Join)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		EnumInfos:         file_game_proto_enumTypes,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
